language: python

python:
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install urllib3==1.26.6
  - pip install black flake8 coverage coveralls

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 --max-line-length=88
  - coverage run manage.py test
  - coverage report

after_script:
  - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls
  
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-west-2
  app: django-tutorial
  env: django-env
  bucket_name: elasticbeanstalk-us-west-2-905418423641
  on:
    branch: main  
