language: python
before_install:
  - pyenv install 3.11
  - pyenv global 3.11
  
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIA5FTZEXVM6RBBE7MK
  secret_access_key: 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
  region: us-west-2
  app: django-tutorial
  env: django-env
  bucket_name: elasticbeanstalk-us-west-2-905418423641
  on:
    branch: main  
